name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master

    - name: Verify Minikube Cluster
      run: kubectl get pods -A

    - name: Build Image Inside Minikube
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo "Verifying built images:"
          docker images

    - name: Deploy to Minikube
      run: |
          kubectl apply -f k8s-node-app.yaml
          kubectl set image deployment/nodejs-app nodejs-app=devopshint/node-app:latest

    - name: Debug Deployment
      run: |
          kubectl get pods -A
          kubectl describe pod -l app=nodejs-app
          kubectl logs -l app=nodejs-app

    - name: Test Service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url
